# All action links for this module

product._add:
  # Which route will be called by the link
  route_name: entity.product.add
  title: 'Add Product'

  # Where will the link appear, defined by route name.
  appears_on:
    - entity.product.collection
    - entity.product.canonical
