# Define the 'local' links for the module

entity.product.settings_tab:
  route_name: product.term_settings
  title: Settings
  base_route: product.term_settings

entity.product.view:
  route_name: entity.product.canonical
  base_route: entity.product.canonical
  title: View

entity.product.page_edit:
  route_name: entity.product.edit_form
  base_route: entity.product.canonical
  title: Edit

entity.product.delete_confirm:
  route_name:  entity.product.delete_form
  base_route:  entity.product.canonical
  title: Delete
  weight: 10


