'delete product entity':
  title: Delete product entity content.
'add product entity':
  title: Add product entity content
'view product entity':
  title: View product entity content
'edit product entity':
  title: Edit product entity content
'administer product entity':
  title: Administer product settings


